build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related APIs"
  contactDetails:
    name: "Rahul Sharma - Developer"
    email: "studyjava2@gmail.com"
  onCallSupport:
    -9584229436
    -9334889130








